### ISSUE TITLE
Always-false test in parseEncodedTimezone

### ISSUE THREAD

**Issue by stephenPspackman** [kshetline/tubular_time#23]
You would appear to have suffered some editing misfortune.
https://github.com/kshetline/tubular_time/blob/5475c85a8bf23d1461e5bb0bcd95c162e469b960/src/timezone.ts#L882-L883

**Comment by kshetline** [comment]
Good catch!

**Comment by kshetline** [comment]
By the way, what tool did you use to spot this problem? I used Intellij IDEA most of the time when working on this code (sometimes VS Code), and IDEA's inspections are usually pretty good about catching this sort of problem. In this particular case, however, the code above doesn't get flagged.

**Comment by stephenPspackman** [comment]
Eyeballs :-}.

(I'm trying, or thinking of tying, to squeeze some timezone data into a disturbingly small footprint and I came looking for inspiration and/or an idea of how much effort will be involved and/or something that could be used as a front end—I suspect I'm doomed by the constraints to do my own table packing.)

**Comment by kshetline** [comment]
I've fixed the bug and published an update.

The bug was that the second `insertTransitions[0]` should have been `insertTransitions[1]`. I still got valid results even with the bug, but that's perhaps because I hadn't specifically tested a southern hemisphere timezone with DST. The worst case error was a little confusion in the earliest historic DST transition for a timezone.

For your own specific problem, can you rely on users have an up-to-date web browser, or a recent version of Node.js?

If so, the built-in JavaScript `Intl` library already contains full IANA timezone data, only not in a fully-exposed manner. For instance, `Intl` won't give you a list of the timezone names it knows about, and won't give you direct access to timezone transition data. But it will convert between timezones for you, treating timezones mostly as an issue of formatting and parsing.

Right in the neighborhood of where you spotted this bug is where I call a method which can extract the transition data if you needed that. You'd have to have your own list of timezone names to feed into that code.

**Comment by stephenPspackman** [comment]
Mm, no, no full modern libraries, no browser, not much storage, and in any
case the things I need most are, ironically, interactive offline browsing
of zones, and transitions (I mean, you *can* search for them, I think I've
done it in the past, but…). While I'll admit to reinventing the occasional
wheel for love or aesthetics, I think(?) that's probably not what I'm doing
today.

But, yeah, it was actually reading through to see where I could tap the
transition data out to do some experiments with data representation that I
found the bug—so that route was pretty much what I had in mind. Thanks!!
